"""add_mail_ids_table

Revision ID: 1c134baba1eb
Revises: bca25a6b931a
Create Date: 2025-12-08 00:53:16.205481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1c134baba1eb'
down_revision: Union[str, Sequence[str], None] = 'bca25a6b931a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registeredmailids',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registeredmailids_mail_id'), 'registeredmailids', ['mail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registeredmailids_mail_id'), table_name='registeredmailids')
    op.drop_table('registeredmailids')
    # ### end Alembic commands ###
